<!doctype html>
<html lang="en">
	<head>
		<?php require('../Communs/header.php') ?>
		<title>Page Forum </title>
	</head>
	<body>
		<?php require('../Communs/navbar.php') ?>
		<main role="main" class="container">
			<h1> · Fonctions de classeCDO : Chef D'Orchestre. On le reconnaît facilement à sa grande (...) gueule. Un mystérieux instinct le pousse à lancer les chants Faidherbards. Si vous passez devant le foyer, vous l'apercevrez souvent avec une bière à la main.KS : Comme son nom l'indique, il s'occupe des Khestions de Sous. Sérieux et honnête, il récolte l'argent pour diverses occasions (Chasse aux Trésors, repas de classe, khâlots...) ; tout le bénéfice qu'il en tire doit automatiquement être transformé en potentiel éthylique pour Anciens.Tan φ : Il est le Cronos de nos humeurs matinales. Il orne quotidiennement le tableau de ses contrepètries les plus raffinées (décalez donc les sons que débite sa bouche), et décompte les jours, heures, minutes, secondes de détention dans l'univers carcéral de Faidherbe. Vous l'embrasserez donc la veille des vacances, et le désosserez à l'issue d'icelles.Suicide : Elève khrâsh-test.Miss : SSSSSSSSSSSEKHSSSSSSSSSSSSSSSSSSSSSSSSS !!! Quand, précédée de son opulente poitrine, elle pénétre dans la classe et qu'elle pose sur vous ses yeux troublants, une décharge d'adrénaline et de testostérone ébranle votre conscience (reste tranquille kiki !). Vous ressentirez subitement l'envie folle d'embrasser votre voisine. On l'observe facilement au foyer, un jus de carotte dans la main, un surfer dans ses bras.Sex B : Sex Bomb, Sex Bomb... Equivalent masculin de la Miss.PDM : Le Préfet Des Mœurs est une créature tout à fait spéciale de la faune faidherbarde. En effet, que fait le Taupin moyen lorsqu'il ne prend pas les cours ? Il mate !!! Jeunes filles, ne tremblez plus, le PDM est là pour protéger votre vertu. Il aide à la création de groupes d'études... Mixtes, bien sûr. Néanmoins, il peut parfois lui aussi éprouver des sentiments humains, donc méfiez-vous !PR : Panthère Rose. Toute douce à caresser...Z : Etre sublime par qui tout commence et tout finit. Il tient la feuille d'abscences et le cahier de textes. Sécheur invétéré, fais-toi son ami(e) (facile : offre-lui à boire !), ou fais-toi Z. C'est également le cordon ombilical qui relie la classe au reste des instances administratives.Σ : Suceur Infirme de Gnômes Malades et Amorphes ; votre bête noire, car il gère la roulette des khôlles. Si au début de l'année, on demande un pigeon pour être Sigma, surtout ne pas broncher : les récompenses ne seront pas à la hauteur du labeur à fournir.PO : Puceau Officiel. Quelques cheveux qui poussent sur la gueule, une tête à chier dessus, un éternel air niais, un rire de baleine, un sourire à pleurer et un regard... Ah !! Son salut, éclaircir le mystère de sa vie : qu'est-ce donc cette anomalie corporelle qui ne cesse de croître et de décroître ?FO : Frigide Officielle. Equivalent féminin du PO.LSD : Naine fellatrice (L Suce Debout).Roi et Reine des Jackys : Spécifique à la HX5, ils sont choisis entre tous par leurs prédécesseurs afin de régner sur les Jackys du monde entier.</main>
			<?php require('../Communs/scriptjava.php') ?>
		</body>
	</html>
